"""
Clinical Summary Validation Agent.

Validates the generated clinical summary against
the source document and writes validation issues
into WorkflowState.validation.issues.
"""

from __future__ import annotations

from typing import Any

from framework.prompts.clinical_summary_validation_prompt import (
    ClinicalSummaryValidationPrompt,
)

from framework.schemas.clinical_summary_validation_schema import (
    ClinicalSummaryValidationResponse,
)

from framework.state.validation_state import (
    ValidationIssue,
)

from framework.state.workflow_state import (
    WorkflowState,
)

from framework.utils.json_parser import (
    parse_json_response,
)


class ClinicalSummaryValidationAgent:
    """
    Validates a generated clinical summary against
    source clinical information.
    """

    def __init__(
        self,
        router: Any,
        prompt_registry: Any,
        logger: Any | None = None,
    ) -> None:

        self.router = router

        self.prompt_registry = (
            prompt_registry
        )

        self.logger = logger

    async def execute(
        self,
        state: WorkflowState,
    ) -> WorkflowState:
        """
        Execute clinical summary validation.
        """

        if self.logger:

            self.logger.info(
                "Starting Clinical Summary Validation."
            )

        # ------------------------------------------------------
        # Get clinical summary
        # ------------------------------------------------------

        summary = state.clinical_summary

        # ------------------------------------------------------
        # Convert source document into prompt payload.
        # ------------------------------------------------------

        source_data: dict[str, Any] = {
            "document_id": (
                state.document.document_id
            ),
            "file_name": (
                state.document.file_name
            ),
            "pages": [
                {
                    "page_number": page.page_number,
                    "content": page.content,
                }
                for page in state.document.pages
            ],
        }

        # ------------------------------------------------------
        # Convert clinical summary into JSON-compatible data.
        # ------------------------------------------------------

        clinical_summary = (
            summary.model_dump()
        )

        # ------------------------------------------------------
        # Build prompt
        # ------------------------------------------------------

        prompt_template = (
            self.prompt_registry.get(
                "clinical_summary_validation"
            )
        )

        prompt = prompt_template.build(
            source_data=source_data,
            clinical_summary=clinical_summary,
        )

        # ------------------------------------------------------
        # LLM call
        # ------------------------------------------------------

        response = await self.router.chat(
            capability=(
                "clinical_summary_validation"
            ),
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert healthcare "
                        "clinical validation system. "
                        "Return only valid JSON."
                    ),
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )

        # ------------------------------------------------------
        # Extract response content
        # ------------------------------------------------------

        result_text = (
            response[
                "choices"
            ][0][
                "message"
            ][
                "content"
            ]
        )

        # ------------------------------------------------------
        # Parse and validate
        # ------------------------------------------------------

        parsed = parse_json_response(
            result_text,
            ClinicalSummaryValidationResponse,
        )

        # ------------------------------------------------------
        # Reset validation issues generated by this stage.
        #
        # IMPORTANT:
        # ValidationState is shared by the workflow.
        # We only replace the issues generated here.
        # ------------------------------------------------------

        state.validation.issues = []

        # ------------------------------------------------------
        # Convert schema issues into WorkflowState issues.
        # ------------------------------------------------------

        for issue in parsed.issues:

            state.validation.issues.append(
                ValidationIssue(
                    code=issue.code,
                    message=issue.message,
                    severity=issue.severity,
                )
            )

        # ------------------------------------------------------
        # Store validation metadata.
        #
        # ValidationState intentionally contains only
        # "issues", so metadata is stored in the clinical
        # summary metadata rather than assuming fields exist
        # on ValidationState.
        # ------------------------------------------------------

        summary.metadata[
            "clinical_summary_validation"
        ] = {
            "valid": parsed.valid,
            "confidence": parsed.confidence,
            "notes": parsed.notes,
            "issue_count": len(
                parsed.issues
            ),
            "metadata": parsed.metadata,
        }

        # ------------------------------------------------------
        # Checkpoint
        # ------------------------------------------------------

        state.checkpoint.stage = (
            "clinical_summary_validation_completed"
        )

        # ------------------------------------------------------
        # Logging
        # ------------------------------------------------------

        if self.logger:

            self.logger.info(
                "Clinical Summary Validation Complete. "
                f"Valid={parsed.valid}, "
                f"Issues={len(parsed.issues)}, "
                f"Confidence={parsed.confidence}."
            )

        return state